name: USA Dream
favicon: null
layout_spectrum: 0.6650696746073663
typography_spectrum: 0.8434339931700379
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1738820574246347
  lightness: 0.4329782531131059
  saturation: 0.6752961364109069
  rhythmicContrast: 0.7491452628746629
purpose: []
